name: Python Calculator CI

# Trigger workflow
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  run-calculator:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Get repository code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Setup Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      # Step 3: Run calculator program
      - name: Run Calculator Script
        run: |
          echo -e "1\n5\n3" | python calculator.py
